server:
  port: 0

file:
  upload-dir: uploads

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
