server:
  port: 0

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/campusdocs_submission_db

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}